name: Update Vaccine Code Mappings and Create Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    outputs:
      new_commit: ${{ steps.commitChanges.outputs.NEW_COMMIT }}
      release_name: ${{ steps.releaseVersion.outputs.RELEASE_NAME }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          
      - name: Run CDC Rake task
        run: bundle exec rake load_cdc_mapping

      - name: Set Release Version
        id: releaseVersion
        run: echo "RELEASE_NAME=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Commit Vaccine Code Mapping Changes
        id: commitChanges
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add vaccine-code-mapping.json
          git add miic-mapping.csv
          if ! git diff --staged --quiet; then
            git commit -m "💉 Update vaccine code mappings for ${{ steps.releaseVersion.outputs.RELEASE_NAME }}"
            git push origin HEAD:$BRANCH_NAME
            echo "NEW_COMMIT=1" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "NEW_COMMIT=0" >> $GITHUB_OUTPUT
          fi
      - name: Create and Push Release Tag
        if: ${{ steps.commitChanges.outputs.NEW_COMMIT == 1 }}
        run: |
          git tag ${{ steps.releaseVersion.outputs.RELEASE_NAME }}
          git push origin ${{ steps.releaseVersion.outputs.RELEASE_NAME }}

      - name: Release
        if: ${{ steps.commitChanges.outputs.NEW_COMMIT == 1 }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vaccine-code-mapping.json,
            miic-mapping.csv
          tag_name: ${{ steps.releaseVersion.outputs.RELEASE_NAME }}
