name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          
      - name: Run Rake task
        run: bundle exec rake load_mapping

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: vaccine-code-mapping.json
